apiVersion: apps/v1
kind: Deployment
metadata:
  name: zcbusserver-deployment
  namespace: zcbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zcbusserver
  template:
    metadata:
      labels:
        app: zcbusserver
    spec:
      nodeSelector:
        kubernetes.io/hostname: db04
      containers:
      - name: zcbusserver
        image: reg.zbomc.com/zcbus_server/zcbus_server:v3.0.5
        # 只有镜像不存在时，才会进行镜像拉取
        imagePullPolicy: IfNotPresent
        env:
        - name: ZCBUS_CONTAINER
          value: 
        - name: dbhost
          value: 'mysql-master'
        - name: dbuser
          value: 'SFVVTjo'
        - name: dbpwd
          value: 'SFVVTjo'
        - name: dbport
          value: '3306'
        - name: database
          value: "zcbus"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zcbusweb-deployment
  namespace: zcbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zcbusweb
  template:
    metadata:
      labels:
        app: zcbusweb
    spec:
      containers:
      - name: zcbusweb
        image: reg.zbomc.com/zcbus_web/zcbus_web:v3.0.4
        # 只有镜像不存在时，才会进行镜像拉取
        imagePullPolicy: IfNotPresent
        env:
        - name: dbhost
          value: mysql-master
        ports:
          - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: zcbusweb-svc
  labels:
    app: zcbusweb
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: None
  selector:
    app: zcbusweb